# 矩阵

## 矩阵生成

In [15]:
import numpy as np

In [16]:
# 生成一个 4x3 矩阵，取值范围：[0, 1) 随机浮点数
a1 = np.random.random((4,3))
a1

array([[0.31813235, 0.05361111, 0.6018653 ],
       [0.66347416, 0.94872308, 0.5909818 ],
       [0.69346205, 0.84542219, 0.34127347],
       [0.97618735, 0.05212129, 0.11100735]])

In [17]:
# 生成一个 4x3 矩阵，取值范围：[1, 11) 随机整数
a2 = np.random.randint(1, 11, (4,3))
a2

array([[ 4,  9,  2],
       [ 3,  9,  1],
       [ 5,  9, 10],
       [ 2,  4,  3]])

In [19]:
# 生成一个 4x3 矩阵，每个元素都是 1
a3 = np.ones((4, 3))
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# 生成一个 4x3 矩阵，每个元素都是 0
a4 = np.zeros((4, 3))
a4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 生成一个 4x3 矩阵，取值范围：{2, 25).步长为 2
a5 = np.mat(np.arange(2, 25, 2)).reshape(4, 3)
a5

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]])

In [22]:
# 自定义一个 4x3 矩阵
a6 = np.mat('1 2 3;4 5 6;7 8 9;10 11 12')
a6

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

## 访问矩阵元素

In [23]:
a = np.mat('1 2 3;4 5 6;7 8 9;10 11 12')
a

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [24]:
# 获取矩阵的行数和列数
m, n = np.shape(a)

In [25]:
m

4

In [26]:
n

3

In [27]:
# 访问第1行第1列和第3行第2列
a_11, a_32 = a[0, 0], a[2, 1]

In [28]:
a_11

1

In [29]:
a_32

8

In [30]:
#访问第2行
a_r2 = a[1]
a_r2

matrix([[4, 5, 6]])

In [32]:
#访问第2列
a_c2 = a[:, 1]
a_c2

matrix([[ 2],
        [ 5],
        [ 8],
        [11]])

## 矩阵运算

In [33]:
a = np.mat('1 2 3;4 5 6;7 8 9;10 11 12')
b = np.ones((4, 3))

In [34]:
print('a = \n{}\nb = \n{}'.format(a, b))

a = 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 矩阵加减

In [42]:
d1 = a + b
d1

matrix([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.]])

In [43]:
# 等同于 a + b
d2 = np.add(a, b)
d2

matrix([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.]])

In [44]:
d3 = a - b
d3

matrix([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [46]:
# 等同于 a - b
d4 = np.subtract(a, b)
d4

matrix([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

### 矩阵数乘

In [47]:
d5 = a * 2
d5

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]])

In [48]:
# 等同于 a * 2
d6 = np.multiply(a, 2)
d6

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]])

### 矩阵乘法

In [49]:
# 定义一个 3x4 矩阵
c = np.ones((3, 4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
d7 = np.dot(b, c)
d7

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

### 矩阵转置

In [52]:
d8 = a.T
d8

matrix([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

In [53]:
d9 = np.transpose(a)
d9

matrix([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

## 求矩阵的转置和逆

In [61]:
# 定义一个 4x4 单位矩阵
E = np.eye(4, 4)
E

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
# 定义一个 2x2 矩阵
a = np.mat('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [63]:
# a 的逆矩阵
b1 = a**-1
b1

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [64]:
# 等同于 a**-1
b2 = np.linalg.inv(a)
b2

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [65]:
# 一个矩阵和它的逆矩阵相乘，结果四舍五入保留整数
c = np.around(np.dot(a, b2), decimals=1)
c

array([[1., 0.],
       [0., 1.]])

## 矩阵的秩

In [67]:
A = np.mat('1 2 3;-2 5 4;0 -1 1;3 0 2')
A

matrix([[ 1,  2,  3],
        [-2,  5,  4],
        [ 0, -1,  1],
        [ 3,  0,  2]])

In [68]:
r = np.linalg.matrix_rank(A)
r

3