# 向量（Vector）和行列式（Determinant）

## 向量的加减和数乘

In [1]:
import numpy as np

In [2]:
a = np.array([-1, 2])
b = np.array([3, 1])

In [7]:
c = a + b
c

array([2, 3])

In [8]:
d = a * 2
d

array([-2,  4])

In [9]:
e = b * (-3)
e

array([-9, -3])

## 向量的点积

如果 A 和 B 都是 n 维向量，它们的点积就是二者分量的乘积之和：

if $\quad A=\left\langle a_{1}, a_{2}, \cdots, a_{n}\right\rangle, \quad B=\left\langle b_{1}, b_{2}, \cdots, b_{n}\right\rangle, \quad$ then $\quad A \cdot B=\sum_{i=1}^{n} a_{i} b_{i}$

In [13]:
a = np.array([-2, 2])
b = np.array([2, 2])

In [15]:
# 计算点积（内积）
f = np.inner(a, b)
f

0

## 向量的叉积

二维空间，两个向量的叉积是这样定义的：
$$
A=\left[\begin{array}{l}
{a_{1}} \\
{a_{2}}
\end{array}\right], \quad B=\left[\begin{array}{l}
{b_{1}} \\
{b_{2}}
\end{array}\right]
$$

$$
A \times B=\left|\begin{array}{ll}
{a_{1}} & {a_{2}} \\
{b_{1}} & {b_{2}}
\end{array}\right|=a_{1} b_{2}-a_{2} b_{1}
$$

三维空间向量：
$$
A=\left[\begin{array}{l}
{a_{1}} \\
{a_{2}} \\
{a_{3}}
\end{array}\right], \quad B=\left[\begin{array}{l}
{b_{1}} \\
{b_{2}} \\
{b_{3}}
\end{array}\right]
$$

$$
A \times B=\left|\begin{array}{lll}
{\hat{i}} & {\hat{j}} & {\hat{k}} \\
{a_{1}} & {a_{2}} & {a_{3}} \\
{b_{1}} & {b_{2}} & {b_{3}}
\end{array}\right|=\left\langle\hat{i}\left|\begin{array}{ll}
{a_{2}} & {a_{3}} \\
{b_{2}} & {b_{3}}
\end{array}\right|, -\hat{j}\left|\begin{array}{cc}
{a_{1}} & {a_{3}} \\
{b_{1}} & {b_{3}}
\end{array}\right|, \hat{k}\left|\begin{array}{ll}
{a_{1}} & {a_{2}} \\
{b_{1}} & {b_{2}}
\end{array}\right|\right\rangle
$$
$\hat{i}$, $\hat{j}$, $\hat{k}$ 是每个维度的单位向量

In [16]:
a = np.array([1, 2, 1])
b = np.array([1, -1, 1])

In [18]:
g = np.cross(a, b)
g

array([ 3,  0, -3])

## 行列式计算

In [19]:
# 定义两个矩阵
a = np.mat('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [20]:
b = np.mat('2 2 0;1 0 1;0 1 1')
b

matrix([[2, 2, 0],
        [1, 0, 1],
        [0, 1, 1]])

In [21]:
det_a = np.linalg.det(a)
det_b = np.linalg.det(b)

In [22]:
det_a

-2.0000000000000004

In [23]:
det_b

-4.0